### ISSUE TITLE
QoL: vomit particles still missing

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#180]
you do make vomit sound with higher player contamination, but no particles appear
i know its a badly small detail but still

**Comment by Shibva** [comment]
This is me pushing this as it's needed. It did exist but my best guess on why it doesn't now was due to the re-texturing of certain blocks that were being used for the color; if that's the case, then balefire terrain blocks would be a viable substitute. The reason why I think it's needed is because the "vomit" is a visual indicator of not only where it's coming from but also an indicator that you lost some of your hunger points.


In addition it also seems that asbestos gas blocks are not rarely producing particles (if my memory is right, they exert white puffs like how coal dust gas blocks emit black smoke particles)

Same could be said about the coughing thing but that one I'm not 100% sure on if it even was a thing or my memory acting up.

**Comment by ntmleafia** [comment]
fun fact: before I played 1.7 one I couldn't even tell the sound was supposed to be vomit lol

**Comment by Alcatergit** [comment]
Fixed it - will be in next update
