### ISSUE TITLE
Incompatibility problem with crude oil and galacticraft

### ISSUE THREAD

**Issue by Ethanedc** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#275]
Using the version of ntm 1.9.8 with Galacticraft 4.0.6 cause a incompatibility with the crude oil and fluid.oilgc.

**Comment by Shibva** [comment]
Hey! This was not fixed?! Damn

**Comment by Shibva** [comment]
To add context; I was helping test the original port when drillgon was working on it; I made the same sort of discovery regarding how gc oil was incompatible and because of the fluid duct system having their oil take priority it made it impossible to boil the oil or something

Yeah if this is what's going on for you then this is a major compat issue

**Comment by Ethanedc** [comment]
Its possible to make a temporal fix? i touched the code time ago with a problem with the oil sucking function making an stackoverflow due to recursive function

**Comment by Shibva** [comment]
You could use the craft Tweaker handler to add the oil to the boiler as a recipe

**Comment by Ethanedc** [comment]
ok im going to try it, thx

**Comment by Alcatergit** [comment]
Fixed it - the one block boilers just did not allow the fluid to be injected. The big multiblock boiler can already do all the boil recipes.
