### ISSUE TITLE
(corrected) suggestion rad seal checker

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#289]
#277 Correction for this. Changed the title too.
Sorry for poor description. **What I've meant is**, checks if area is leaked and has radiation effect on the entire chunk, or is successfully separated as "pockets" as said in codes

For example, this is sealed
![スクリーンショット (7194)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/9f484d44-1ad2-413d-a264-1a6dfd7aceea)
This is not sealed
![スクリーンショット (7195)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/755f1e34-e2ae-45a1-8932-fb06b81080cb)

This one is really obivious and shouldn't need any tool to find unless you're really blind, right?

But when it gets to something like this:
![スクリーンショット (7197)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/a5de3f74-107a-4536-ad15-1d0f679b224d)
These blocks never protect you from rads. Ofcourse, why would a computer shield radiations?
Don't worry, there are actually concrete blocks behind these encasing this area entirely.
![スクリーンショット (7198)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/b90e0648-fa29-42cd-a354-155feff36c75)
...or is it?
(maximum level geiger counter sounds)

**Comment by Alcatergit** [comment]
That is a pretty interesting suggestion. But due to the way the 3d chunk radiation works it is not possible without a major rewrite.
One thing you can do tho is to use some clever redstone contraption to automate it.

Step 1 make a redstone activeable chunk radiation source
Step 2 place radiation sensor inside bunker
Step 3 activate the radiation source for just a few seconds - like a radiation ping
Step 4 if there is a leak then the radiation sensor in bunker will notice - if not then there is no leak.
Step 5 enjoy

**Comment by ntmleafia** [comment]
Although I've already done something like that before, your idea did help.
![a2bf214b6cb24547a2989d97a48ac7e0](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/daeb036d-c809-4e63-8129-7e85cb4579e4)
Using incredibly low contaminating blocks helped detecting seal without killing the environment.
Thank you for help!

P.S. For one who came here looking for same issue, the "incredibly low contaminating block" I used is uranium sand
