### ISSUE TITLE
(Bug) Conveyor Inserter and Ejectors

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#307]
### Both:
"Crane"
![7e4ff40b98afb3ec843276f0748347c8](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/e231a561-d3bb-4a2b-b471-9cb47298b406)
![8d3fd3215fa32c3fd5e10cb1ab610deb](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/13477a47-0ebf-4151-82cf-541ccce8d20d)
So they inserts and ejects from a crane and not conveyor? (<= joke btw)
....Maybe that could be inspired of. A crane that runs on rails attached to ceiling beams and takes items from conveyors below under certain conditions, or as a thing programmable with OpenComputers, idk lol.

### Ejector only:
Can't remove filter once set
![7dc48e641cb12334fdd3cdd08070c30a](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/57cefba7-33cb-4ed2-b996-f8c0f9a171d9)
This grass is forever trapped in that slot

**Comment by Shibva** [comment]
To add on to this; further testing suggests that there is a mismatch what thing the inventory is being inserted into the ejector; as it will put the items into the FILTER slot instead of the actual output slot

Edit: this was found using the Extractor 
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/4f041285-dd36-4800-86ad-bafe8162f131)
EDIT II: OK this is another issue for the drill lel

**Comment by Shibva** [comment]
Made a pull request #316 to fix it on the EN_US file; needs proper translation for the other languages

**Comment by Alcatergit** [comment]
Conveyor filter Insertion and Extraction is fixed
