### ISSUE TITLE
Crash server when join

### ISSUE THREAD

**Issue by mohamedcraft** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#324]
When i start server with NTM V2.0.0 start normally but when i join the server close (crash) and in game say /server closed\
Note: when i use V1.9.8 i can join
Please fix it quickly Because i want to play the last update for NTM mod
Reason→{Galacticraft Sealable Doors}
Crash Report(https://mclo.gs/mUo8Jzh)

**Comment by Shibva** [comment]
Taking a quick client at the crash report it seems like a resource is missing

I'm not having this issue, yet I'm not using Galactic craft, so I'm questioning if one of the changes to make the door sealable did not get properly imported somewhere; since noclassdeaf usually indicate that there's a missing .class file

**Comment by OppaiHacker** [comment]
In NTM V2.0.1 bug is fixed

**Comment by Alcatergit** [comment]
Fixed in 2.0.1
