### ISSUE TITLE
Wearing the dnt nano suit drains energy quickly

### ISSUE THREAD

**Issue by username1234567890f** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#330]
I'm wearing a DNT nano suit and haven't done anything, but my energy is decreasing at a very rapid rate
![2024-02-16_10 57 35](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/159400635/8d100616-5ed1-4b81-8e7e-3f583742e1f7)
3 seconds later
![2024-02-16_10 57 39](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/159400635/452b7c76-9f48-401a-ad46-3fae2facaa77)

**Comment by 3114396pig** [comment]
it is because at com.hbm.items.ModItems (line 931) the "drain" value is 10000
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/88887515/b831550a-d992-4324-88d4-c4dbccf5090d)
and every tick it consumes drain - the discharge rate of the self charge battery (if it is held)
![2024-02-17 132613](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/88887515/a232f44b-eeb2-4e2a-9c65-d0debe277981)
maybe it is designed to be that fast
