### ISSUE TITLE
Why the hell does lung cancer not go away after death

### ISSUE THREAD

**Issue by Logic242** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#54]
Not only does the carbon mask not work, just like the 1.12.2 reloaded version.

Lung disease does not go away after /suicide or dying.

whats the point of this port, if it fixes barely anything of the original 1.12.2 reloaded version and is mostly just a ripped repost

**Comment by KaxelOleg** [comment]
Try to disable the mechanics of lung cancer in the config until the update with the bug fix comes out, and then go in, and if necessary, turn it on again. Maybe it will reboot this way. Another possible option is to enter the creative and exit it, since when you enter the creative, the data about your lungs are overwritten and put in the 0 values.

**Comment by Alcatergit** [comment]
"whats the point of this port, if it fixes barely anything of the original 1.12.2 reloaded version and is mostly just a ripped repost"
I made a big update to 1.12.2 so reloaded copied that from this version not the other way. It also adds many new features like the new DFC and S.A.F.E reactors.

**Comment by Alcatergit** [comment]
Ill look into what is causing that

**Comment by Alcatergit** [comment]
Fixed
