### ISSUE TITLE
Is there any way to modify the heat diffusion of RBMKs?

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#66]
I want to build an RBMK capable of rapidly burning up fuel for the production of bismuth and such. But regardless of how much cooling I put into it, it will always melt down with the extreme levels of flux I produce in the core. The fuel doesn't dissipate the heat from the rod's skin fast enough. I wonder if there's a setting to modify the diffusion ratio?

**Comment by xenoulexi** [comment]
It would be also neat if you can add RBMK rods that do not produce heat, but rather modify the neutron flux in some way. During my attempts to create a fuel burning RBMK, I have, for example, had multiple unobtanium rods channeling their neutron flux directly into a thorium rod which I intended to act as a kind of lens to focus that neutron flux toward a receiving plutonium rod. But that didn't work as planned as the rod acted more like a moderator/absorber than anything else, actually lowering the overall amount of neutron flux despite emitting flux.

**Comment by DNIWE041** [comment]
Use alot more cooling, for example: if you want use balefire in reactor you need around 8 boilers in ultra-dense mode for only ONE fuel rod.
You can't change heat diffusion i think.
And tip: for bismuth use irradiation channel and make lead-209, than make RTG pellet from it and wait ~20000 tick in RTG generator for depletion to bismuth pellet - now you have 3 bismuth billet. More easier if you have high flux for irradiation channel. One problem - lead-209 is 10000 rad\sec for ingot.

And also maybe you can run reactor in ReaSim mode because in this mode all columns can be use as boilers in ultra-dense mode. Also this mode changes some principles of how rbmk works.

**Comment by blue-bird1** [comment]
you need setting  /gamerule dialDiffusionMod or   dialPassiveCooling or dialHeatProvision

**Comment by blue-bird1** [comment]
But even when set to the maximum, If you use 1-degree fuel rods, e.g MEU. its upper limit still cannot exceed 1500/t, maxHeat is 1500., it is a hardcode
